### ISSUE TITLE
Use string_view instead of char*

### ISSUE THREAD

**Issue by claymcleod** [stjude/fqlib#12]
Given the discussions in our last development meeting, I think we need a higher performing strategy than C++ strings but need a little bit more functionality than plain C strings. In particular, we want to have a strategy to cache the length and have some utility methods that are included in the C++ string implementation. Seems like `string_view` is a great solution: it was added in c++17, but I think that's fair game here.

**References**

* https://en.cppreference.com/w/cpp/header/string_view
* http://www.modernescpp.com/index.php/c-17-avoid-copying-with-std-string-view

**Comment by claymcleod** [comment]
Ping @adamdingliang @davisem @jsunny23

**Comment by zaeleus** [comment]
No longer applicable after 07f168c.
