### ISSUE TITLE
Avoid nuking the root directory when running `make clean`

### ISSUE THREAD

**Issue by zaeleus** [stjude/fqlib#13]
Both `build/` and `dist/` do not necessarily exist when `make` is run, setting their respective variables `BUILDDIR` and `DISTDIR` to empty strings. When invoking the `clean` target, it effectively executes `rm -rf /*`.

## Steps to reproduce

```
$ cd /tmp
$ git clone https://github.com/stjude/fqlib.git
$ cd fqlib
$ make --dry-run clean
rm -rf /tmp/fqlib/fqlib/*.c /tmp/fqlib/fqlib/*.cpp /tmp/fqlib/fqlib/*.html /tmp/fqlib/fqlib/*.so /tmp/fqlib/fqlib/__pycache__ /* /*
```
Note the final two arguments in the output.

**Comment by claymcleod** [comment]
Agree that not rimraf-ing `/` is a feature. Just submit a pull.
