### ISSUE TITLE
generate profiling data

### ISSUE THREAD

**Issue by davisem** [stjude/fqlib#6]

**Comment by adamdingliang** [comment]
What is the profiling data are we trying to generate?

**Comment by claymcleod** [comment]
I think we start with simple runtime for the core pieces of `fastq.pyx` without any validators running to see 

- How does the speed compare to other tools?
- Can we make sure that we don't regress in speed (relatively speaking)?

From there, I think getting profiling on different pieces relative to each of the validators might be a good use of time. Especially in the case where there might be problem areas, like memory for the duplicate read names validator.

**Comment by claymcleod** [comment]
@davisem Any update on this?
